# -*- coding: utf-8 -*-
"""Registration_login.ipynb

Automatically generated by Colaboratory.


"""

import csv
import re   


def register():
  print("Registartion form...")
  with open("registration.csv",mode="a",newline='') as f:
    writer=csv.writer(f,delimiter=",")
    writer.writerow(["email","password"])
    while True:
      email_pattern=r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
      pwd_pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{5,15}$"
      email=input("enter your mail adress: ")
      password=input("enter the password: ")
      if re.search(email_pattern,email) and re.search(pwd_pattern,password):
        data=[email,password]
        writer.writerow(data)
        ch=input("do you want to enter more records(Y/N) : ")
        if ch in 'Nn':
          break
    f.close() 
      

register()

def login():
  print("Login here.... ")
  f= open("registration.csv","r")
  Found=0
  email=input("Enter email : ")
  password = input("Enter  password: ")
  reader=csv.reader(f, delimiter=",")
  next(reader)
  for i in reader:
    if i[0] == email:
      print("you are logged in!")
      Found=1
  f.close()
  if Found==0:
    print("No record found....!") 
    print("User not found,please register here....!!") 
    register()  
login()

